// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tinkoff.Proto.InvestApi.V1 {

  /// <summary>Holder for reflection information generated from Protos/common.proto</summary>
  public static partial class CommonReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNQcm90b3MvY29tbW9uLnByb3RvEiV0aW5rb2ZmLnB1YmxpYy5pbnZlc3Qu",
            "YXBpLmNvbnRyYWN0LnYxGh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnBy",
            "b3RvIjsKCk1vbmV5VmFsdWUSEAoIY3VycmVuY3kYASABKAkSDQoFdW5pdHMY",
            "AiABKAMSDAoEbmFubxgDIAEoBSIoCglRdW90YXRpb24SDQoFdW5pdHMYASAB",
            "KAMSDAoEbmFubxgCIAEoBSIwCgRQaW5nEigKBHRpbWUYASABKAsyGi5nb29n",
            "bGUucHJvdG9idWYuVGltZXN0YW1wKu4BCg5JbnN0cnVtZW50VHlwZRIfChtJ",
            "TlNUUlVNRU5UX1RZUEVfVU5TUEVDSUZJRUQQABIYChRJTlNUUlVNRU5UX1RZ",
            "UEVfQk9ORBABEhkKFUlOU1RSVU1FTlRfVFlQRV9TSEFSRRACEhwKGElOU1RS",
            "VU1FTlRfVFlQRV9DVVJSRU5DWRADEhcKE0lOU1RSVU1FTlRfVFlQRV9FVEYQ",
            "BBIbChdJTlNUUlVNRU5UX1RZUEVfRlVUVVJFUxAFEhYKEklOU1RSVU1FTlRf",
            "VFlQRV9TUBAGEhoKFklOU1RSVU1FTlRfVFlQRV9PUFRJT04QByrOBgoVU2Vj",
            "dXJpdHlUcmFkaW5nU3RhdHVzEicKI1NFQ1VSSVRZX1RSQURJTkdfU1RBVFVT",
            "X1VOU1BFQ0lGSUVEEAASNQoxU0VDVVJJVFlfVFJBRElOR19TVEFUVVNfTk9U",
            "X0FWQUlMQUJMRV9GT1JfVFJBRElORxABEioKJlNFQ1VSSVRZX1RSQURJTkdf",
            "U1RBVFVTX09QRU5JTkdfUEVSSU9EEAISKgomU0VDVVJJVFlfVFJBRElOR19T",
            "VEFUVVNfQ0xPU0lOR19QRVJJT0QQAxIsCihTRUNVUklUWV9UUkFESU5HX1NU",
            "QVRVU19CUkVBS19JTl9UUkFESU5HEAQSKgomU0VDVVJJVFlfVFJBRElOR19T",
            "VEFUVVNfTk9STUFMX1RSQURJTkcQBRIrCidTRUNVUklUWV9UUkFESU5HX1NU",
            "QVRVU19DTE9TSU5HX0FVQ1RJT04QBhItCilTRUNVUklUWV9UUkFESU5HX1NU",
            "QVRVU19EQVJLX1BPT0xfQVVDVElPThAHEiwKKFNFQ1VSSVRZX1RSQURJTkdf",
            "U1RBVFVTX0RJU0NSRVRFX0FVQ1RJT04QCBIyCi5TRUNVUklUWV9UUkFESU5H",
            "X1NUQVRVU19PUEVOSU5HX0FVQ1RJT05fUEVSSU9EEAkSPAo4U0VDVVJJVFlf",
            "VFJBRElOR19TVEFUVVNfVFJBRElOR19BVF9DTE9TSU5HX0FVQ1RJT05fUFJJ",
            "Q0UQChIsCihTRUNVUklUWV9UUkFESU5HX1NUQVRVU19TRVNTSU9OX0FTU0lH",
            "TkVEEAsSKQolU0VDVVJJVFlfVFJBRElOR19TVEFUVVNfU0VTU0lPTl9DTE9T",
            "RRAMEigKJFNFQ1VSSVRZX1RSQURJTkdfU1RBVFVTX1NFU1NJT05fT1BFThAN",
            "EjEKLVNFQ1VSSVRZX1RSQURJTkdfU1RBVFVTX0RFQUxFUl9OT1JNQUxfVFJB",
            "RElORxAOEjMKL1NFQ1VSSVRZX1RSQURJTkdfU1RBVFVTX0RFQUxFUl9CUkVB",
            "S19JTl9UUkFESU5HEA8SPAo4U0VDVVJJVFlfVFJBRElOR19TVEFUVVNfREVB",
            "TEVSX05PVF9BVkFJTEFCTEVfRk9SX1RSQURJTkcQEEJnChxydS50aW5rb2Zm",
            "LnBpYXBpLmNvbnRyYWN0LnYxUAFaDC4vO2ludmVzdGFwaaICBVRJQVBJqgIa",
            "VGlua29mZi5Qcm90by5JbnZlc3RBcGkuVjHKAhFUaW5rb2ZmXEludmVzdFxW",
            "MWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Tinkoff.Proto.InvestApi.V1.InstrumentType), typeof(global::Tinkoff.Proto.InvestApi.V1.SecurityTradingStatus), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Tinkoff.Proto.InvestApi.V1.MoneyValue), global::Tinkoff.Proto.InvestApi.V1.MoneyValue.Parser, new[]{ "Currency", "Units", "Nano" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Tinkoff.Proto.InvestApi.V1.Quotation), global::Tinkoff.Proto.InvestApi.V1.Quotation.Parser, new[]{ "Units", "Nano" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Tinkoff.Proto.InvestApi.V1.Ping), global::Tinkoff.Proto.InvestApi.V1.Ping.Parser, new[]{ "Time" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///Тип инструмента.
  /// </summary>
  public enum InstrumentType {
    [pbr::OriginalName("INSTRUMENT_TYPE_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    ///Облигация.
    /// </summary>
    [pbr::OriginalName("INSTRUMENT_TYPE_BOND")] Bond = 1,
    /// <summary>
    ///Акция.
    /// </summary>
    [pbr::OriginalName("INSTRUMENT_TYPE_SHARE")] Share = 2,
    /// <summary>
    ///Валюта.
    /// </summary>
    [pbr::OriginalName("INSTRUMENT_TYPE_CURRENCY")] Currency = 3,
    /// <summary>
    ///Exchange-traded fund. Фонд.
    /// </summary>
    [pbr::OriginalName("INSTRUMENT_TYPE_ETF")] Etf = 4,
    /// <summary>
    ///Фьючерс.
    /// </summary>
    [pbr::OriginalName("INSTRUMENT_TYPE_FUTURES")] Futures = 5,
    /// <summary>
    ///Структурная нота.
    /// </summary>
    [pbr::OriginalName("INSTRUMENT_TYPE_SP")] Sp = 6,
    /// <summary>
    ///Опцион.
    /// </summary>
    [pbr::OriginalName("INSTRUMENT_TYPE_OPTION")] Option = 7,
  }

  /// <summary>
  ///Режим торгов инструмента
  /// </summary>
  public enum SecurityTradingStatus {
    /// <summary>
    ///Торговый статус не определён
    /// </summary>
    [pbr::OriginalName("SECURITY_TRADING_STATUS_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    ///Недоступен для торгов
    /// </summary>
    [pbr::OriginalName("SECURITY_TRADING_STATUS_NOT_AVAILABLE_FOR_TRADING")] NotAvailableForTrading = 1,
    /// <summary>
    ///Период открытия торгов
    /// </summary>
    [pbr::OriginalName("SECURITY_TRADING_STATUS_OPENING_PERIOD")] OpeningPeriod = 2,
    /// <summary>
    ///Период закрытия торгов
    /// </summary>
    [pbr::OriginalName("SECURITY_TRADING_STATUS_CLOSING_PERIOD")] ClosingPeriod = 3,
    /// <summary>
    ///Перерыв в торговле
    /// </summary>
    [pbr::OriginalName("SECURITY_TRADING_STATUS_BREAK_IN_TRADING")] BreakInTrading = 4,
    /// <summary>
    ///Нормальная торговля
    /// </summary>
    [pbr::OriginalName("SECURITY_TRADING_STATUS_NORMAL_TRADING")] NormalTrading = 5,
    /// <summary>
    ///Аукцион закрытия
    /// </summary>
    [pbr::OriginalName("SECURITY_TRADING_STATUS_CLOSING_AUCTION")] ClosingAuction = 6,
    /// <summary>
    ///Аукцион крупных пакетов
    /// </summary>
    [pbr::OriginalName("SECURITY_TRADING_STATUS_DARK_POOL_AUCTION")] DarkPoolAuction = 7,
    /// <summary>
    ///Дискретный аукцион
    /// </summary>
    [pbr::OriginalName("SECURITY_TRADING_STATUS_DISCRETE_AUCTION")] DiscreteAuction = 8,
    /// <summary>
    ///Аукцион открытия
    /// </summary>
    [pbr::OriginalName("SECURITY_TRADING_STATUS_OPENING_AUCTION_PERIOD")] OpeningAuctionPeriod = 9,
    /// <summary>
    ///Период торгов по цене аукциона закрытия
    /// </summary>
    [pbr::OriginalName("SECURITY_TRADING_STATUS_TRADING_AT_CLOSING_AUCTION_PRICE")] TradingAtClosingAuctionPrice = 10,
    /// <summary>
    ///Сессия назначена
    /// </summary>
    [pbr::OriginalName("SECURITY_TRADING_STATUS_SESSION_ASSIGNED")] SessionAssigned = 11,
    /// <summary>
    ///Сессия закрыта
    /// </summary>
    [pbr::OriginalName("SECURITY_TRADING_STATUS_SESSION_CLOSE")] SessionClose = 12,
    /// <summary>
    ///Сессия открыта
    /// </summary>
    [pbr::OriginalName("SECURITY_TRADING_STATUS_SESSION_OPEN")] SessionOpen = 13,
    /// <summary>
    ///Доступна торговля в режиме внутренней ликвидности брокера
    /// </summary>
    [pbr::OriginalName("SECURITY_TRADING_STATUS_DEALER_NORMAL_TRADING")] DealerNormalTrading = 14,
    /// <summary>
    ///Перерыв торговли в режиме внутренней ликвидности брокера
    /// </summary>
    [pbr::OriginalName("SECURITY_TRADING_STATUS_DEALER_BREAK_IN_TRADING")] DealerBreakInTrading = 15,
    /// <summary>
    ///Недоступна торговля в режиме внутренней ликвидности брокера
    /// </summary>
    [pbr::OriginalName("SECURITY_TRADING_STATUS_DEALER_NOT_AVAILABLE_FOR_TRADING")] DealerNotAvailableForTrading = 16,
  }

  #endregion

  #region Messages
  /// <summary>
  ///Денежная сумма в определенной валюте
  /// </summary>
  public sealed partial class MoneyValue : pb::IMessage<MoneyValue>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MoneyValue> _parser = new pb::MessageParser<MoneyValue>(() => new MoneyValue());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MoneyValue> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tinkoff.Proto.InvestApi.V1.CommonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MoneyValue() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MoneyValue(MoneyValue other) : this() {
      currency_ = other.currency_;
      units_ = other.units_;
      nano_ = other.nano_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MoneyValue Clone() {
      return new MoneyValue(this);
    }

    /// <summary>Field number for the "currency" field.</summary>
    public const int CurrencyFieldNumber = 1;
    private string currency_ = "";
    /// <summary>
    /// строковый ISO-код валюты
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Currency {
      get { return currency_; }
      set {
        currency_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "units" field.</summary>
    public const int UnitsFieldNumber = 2;
    private long units_;
    /// <summary>
    /// целая часть суммы, может быть отрицательным числом
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Units {
      get { return units_; }
      set {
        units_ = value;
      }
    }

    /// <summary>Field number for the "nano" field.</summary>
    public const int NanoFieldNumber = 3;
    private int nano_;
    /// <summary>
    /// дробная часть суммы, может быть отрицательным числом
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Nano {
      get { return nano_; }
      set {
        nano_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MoneyValue);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MoneyValue other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Currency != other.Currency) return false;
      if (Units != other.Units) return false;
      if (Nano != other.Nano) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Currency.Length != 0) hash ^= Currency.GetHashCode();
      if (Units != 0L) hash ^= Units.GetHashCode();
      if (Nano != 0) hash ^= Nano.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Currency.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Currency);
      }
      if (Units != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Units);
      }
      if (Nano != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Nano);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Currency.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Currency);
      }
      if (Units != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Units);
      }
      if (Nano != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Nano);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Currency.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Currency);
      }
      if (Units != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Units);
      }
      if (Nano != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Nano);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MoneyValue other) {
      if (other == null) {
        return;
      }
      if (other.Currency.Length != 0) {
        Currency = other.Currency;
      }
      if (other.Units != 0L) {
        Units = other.Units;
      }
      if (other.Nano != 0) {
        Nano = other.Nano;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Currency = input.ReadString();
            break;
          }
          case 16: {
            Units = input.ReadInt64();
            break;
          }
          case 24: {
            Nano = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Currency = input.ReadString();
            break;
          }
          case 16: {
            Units = input.ReadInt64();
            break;
          }
          case 24: {
            Nano = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///Котировка - денежная сумма без указания валюты
  /// </summary>
  public sealed partial class Quotation : pb::IMessage<Quotation>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Quotation> _parser = new pb::MessageParser<Quotation>(() => new Quotation());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Quotation> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tinkoff.Proto.InvestApi.V1.CommonReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Quotation() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Quotation(Quotation other) : this() {
      units_ = other.units_;
      nano_ = other.nano_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Quotation Clone() {
      return new Quotation(this);
    }

    /// <summary>Field number for the "units" field.</summary>
    public const int UnitsFieldNumber = 1;
    private long units_;
    /// <summary>
    /// целая часть суммы, может быть отрицательным числом
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Units {
      get { return units_; }
      set {
        units_ = value;
      }
    }

    /// <summary>Field number for the "nano" field.</summary>
    public const int NanoFieldNumber = 2;
    private int nano_;
    /// <summary>
    /// дробная часть суммы, может быть отрицательным числом
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Nano {
      get { return nano_; }
      set {
        nano_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Quotation);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Quotation other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Units != other.Units) return false;
      if (Nano != other.Nano) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Units != 0L) hash ^= Units.GetHashCode();
      if (Nano != 0) hash ^= Nano.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Units != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Units);
      }
      if (Nano != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Nano);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Units != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Units);
      }
      if (Nano != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Nano);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Units != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Units);
      }
      if (Nano != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Nano);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Quotation other) {
      if (other == null) {
        return;
      }
      if (other.Units != 0L) {
        Units = other.Units;
      }
      if (other.Nano != 0) {
        Nano = other.Nano;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Units = input.ReadInt64();
            break;
          }
          case 16: {
            Nano = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Units = input.ReadInt64();
            break;
          }
          case 16: {
            Nano = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///Проверка активности стрима.
  /// </summary>
  public sealed partial class Ping : pb::IMessage<Ping>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Ping> _parser = new pb::MessageParser<Ping>(() => new Ping());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Ping> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tinkoff.Proto.InvestApi.V1.CommonReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Ping() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Ping(Ping other) : this() {
      time_ = other.time_ != null ? other.time_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Ping Clone() {
      return new Ping(this);
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp time_;
    /// <summary>
    ///Время проверки.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Ping);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Ping other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Time, other.Time)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (time_ != null) hash ^= Time.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (time_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Time);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (time_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Time);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (time_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Time);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Ping other) {
      if (other == null) {
        return;
      }
      if (other.time_ != null) {
        if (time_ == null) {
          Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Time.MergeFrom(other.Time);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (time_ == null) {
              Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Time);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (time_ == null) {
              Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Time);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
