// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/stoporders.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tinkoff.Proto.InvestApi.V1 {

  /// <summary>Holder for reflection information generated from Protos/stoporders.proto</summary>
  public static partial class StopordersReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/stoporders.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StopordersReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdQcm90b3Mvc3RvcG9yZGVycy5wcm90bxIldGlua29mZi5wdWJsaWMuaW52",
            "ZXN0LmFwaS5jb250cmFjdC52MRofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFt",
            "cC5wcm90bxoTUHJvdG9zL2NvbW1vbi5wcm90byL4AwoUUG9zdFN0b3BPcmRl",
            "clJlcXVlc3QSDAoEZmlnaRgBIAEoCRIQCghxdWFudGl0eRgCIAEoAxI/CgVw",
            "cmljZRgDIAEoCzIwLnRpbmtvZmYucHVibGljLmludmVzdC5hcGkuY29udHJh",
            "Y3QudjEuUXVvdGF0aW9uEkQKCnN0b3BfcHJpY2UYBCABKAsyMC50aW5rb2Zm",
            "LnB1YmxpYy5pbnZlc3QuYXBpLmNvbnRyYWN0LnYxLlF1b3RhdGlvbhJMCglk",
            "aXJlY3Rpb24YBSABKA4yOS50aW5rb2ZmLnB1YmxpYy5pbnZlc3QuYXBpLmNv",
            "bnRyYWN0LnYxLlN0b3BPcmRlckRpcmVjdGlvbhISCgphY2NvdW50X2lkGAYg",
            "ASgJElcKD2V4cGlyYXRpb25fdHlwZRgHIAEoDjI+LnRpbmtvZmYucHVibGlj",
            "LmludmVzdC5hcGkuY29udHJhY3QudjEuU3RvcE9yZGVyRXhwaXJhdGlvblR5",
            "cGUSTQoPc3RvcF9vcmRlcl90eXBlGAggASgOMjQudGlua29mZi5wdWJsaWMu",
            "aW52ZXN0LmFwaS5jb250cmFjdC52MS5TdG9wT3JkZXJUeXBlEi8KC2V4cGly",
            "ZV9kYXRlGAkgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCIuChVQ",
            "b3N0U3RvcE9yZGVyUmVzcG9uc2USFQoNc3RvcF9vcmRlcl9pZBgBIAEoCSIq",
            "ChRHZXRTdG9wT3JkZXJzUmVxdWVzdBISCgphY2NvdW50X2lkGAEgASgJIl4K",
            "FUdldFN0b3BPcmRlcnNSZXNwb25zZRJFCgtzdG9wX29yZGVycxgBIAMoCzIw",
            "LnRpbmtvZmYucHVibGljLmludmVzdC5hcGkuY29udHJhY3QudjEuU3RvcE9y",
            "ZGVyIkMKFkNhbmNlbFN0b3BPcmRlclJlcXVlc3QSEgoKYWNjb3VudF9pZBgB",
            "IAEoCRIVCg1zdG9wX29yZGVyX2lkGAIgASgJIkMKF0NhbmNlbFN0b3BPcmRl",
            "clJlc3BvbnNlEigKBHRpbWUYASABKAsyGi5nb29nbGUucHJvdG9idWYuVGlt",
            "ZXN0YW1wIpsECglTdG9wT3JkZXISFQoNc3RvcF9vcmRlcl9pZBgBIAEoCRIW",
            "Cg5sb3RzX3JlcXVlc3RlZBgCIAEoAxIMCgRmaWdpGAMgASgJEkwKCWRpcmVj",
            "dGlvbhgEIAEoDjI5LnRpbmtvZmYucHVibGljLmludmVzdC5hcGkuY29udHJh",
            "Y3QudjEuU3RvcE9yZGVyRGlyZWN0aW9uEhAKCGN1cnJlbmN5GAUgASgJEkgK",
            "Cm9yZGVyX3R5cGUYBiABKA4yNC50aW5rb2ZmLnB1YmxpYy5pbnZlc3QuYXBp",
            "LmNvbnRyYWN0LnYxLlN0b3BPcmRlclR5cGUSLwoLY3JlYXRlX2RhdGUYByAB",
            "KAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjgKFGFjdGl2YXRpb25f",
            "ZGF0ZV90aW1lGAggASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIz",
            "Cg9leHBpcmF0aW9uX3RpbWUYCSABKAsyGi5nb29nbGUucHJvdG9idWYuVGlt",
            "ZXN0YW1wEkAKBXByaWNlGAogASgLMjEudGlua29mZi5wdWJsaWMuaW52ZXN0",
            "LmFwaS5jb250cmFjdC52MS5Nb25leVZhbHVlEkUKCnN0b3BfcHJpY2UYCyAB",
            "KAsyMS50aW5rb2ZmLnB1YmxpYy5pbnZlc3QuYXBpLmNvbnRyYWN0LnYxLk1v",
            "bmV5VmFsdWUqdwoSU3RvcE9yZGVyRGlyZWN0aW9uEiQKIFNUT1BfT1JERVJf",
            "RElSRUNUSU9OX1VOU1BFQ0lGSUVEEAASHAoYU1RPUF9PUkRFUl9ESVJFQ1RJ",
            "T05fQlVZEAESHQoZU1RPUF9PUkRFUl9ESVJFQ1RJT05fU0VMTBACKqUBChdT",
            "dG9wT3JkZXJFeHBpcmF0aW9uVHlwZRIqCiZTVE9QX09SREVSX0VYUElSQVRJ",
            "T05fVFlQRV9VTlNQRUNJRklFRBAAEi8KK1NUT1BfT1JERVJfRVhQSVJBVElP",
            "Tl9UWVBFX0dPT0RfVElMTF9DQU5DRUwQARItCilTVE9QX09SREVSX0VYUElS",
            "QVRJT05fVFlQRV9HT09EX1RJTExfREFURRACKpABCg1TdG9wT3JkZXJUeXBl",
            "Eh8KG1NUT1BfT1JERVJfVFlQRV9VTlNQRUNJRklFRBAAEh8KG1NUT1BfT1JE",
            "RVJfVFlQRV9UQUtFX1BST0ZJVBABEh0KGVNUT1BfT1JERVJfVFlQRV9TVE9Q",
            "X0xPU1MQAhIeChpTVE9QX09SREVSX1RZUEVfU1RPUF9MSU1JVBADMsADChFT",
            "dG9wT3JkZXJzU2VydmljZRKKAQoNUG9zdFN0b3BPcmRlchI7LnRpbmtvZmYu",
            "cHVibGljLmludmVzdC5hcGkuY29udHJhY3QudjEuUG9zdFN0b3BPcmRlclJl",
            "cXVlc3QaPC50aW5rb2ZmLnB1YmxpYy5pbnZlc3QuYXBpLmNvbnRyYWN0LnYx",
            "LlBvc3RTdG9wT3JkZXJSZXNwb25zZRKKAQoNR2V0U3RvcE9yZGVycxI7LnRp",
            "bmtvZmYucHVibGljLmludmVzdC5hcGkuY29udHJhY3QudjEuR2V0U3RvcE9y",
            "ZGVyc1JlcXVlc3QaPC50aW5rb2ZmLnB1YmxpYy5pbnZlc3QuYXBpLmNvbnRy",
            "YWN0LnYxLkdldFN0b3BPcmRlcnNSZXNwb25zZRKQAQoPQ2FuY2VsU3RvcE9y",
            "ZGVyEj0udGlua29mZi5wdWJsaWMuaW52ZXN0LmFwaS5jb250cmFjdC52MS5D",
            "YW5jZWxTdG9wT3JkZXJSZXF1ZXN0Gj4udGlua29mZi5wdWJsaWMuaW52ZXN0",
            "LmFwaS5jb250cmFjdC52MS5DYW5jZWxTdG9wT3JkZXJSZXNwb25zZUJnChxy",
            "dS50aW5rb2ZmLnBpYXBpLmNvbnRyYWN0LnYxUAFaDC4vO2ludmVzdGFwaaIC",
            "BVRJQVBJqgIaVGlua29mZi5Qcm90by5JbnZlc3RBcGkuVjHKAhFUaW5rb2Zm",
            "XEludmVzdFxWMWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Tinkoff.Proto.InvestApi.V1.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Tinkoff.Proto.InvestApi.V1.StopOrderDirection), typeof(global::Tinkoff.Proto.InvestApi.V1.StopOrderExpirationType), typeof(global::Tinkoff.Proto.InvestApi.V1.StopOrderType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Tinkoff.Proto.InvestApi.V1.PostStopOrderRequest), global::Tinkoff.Proto.InvestApi.V1.PostStopOrderRequest.Parser, new[]{ "Figi", "Quantity", "Price", "StopPrice", "Direction", "AccountId", "ExpirationType", "StopOrderType", "ExpireDate" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Tinkoff.Proto.InvestApi.V1.PostStopOrderResponse), global::Tinkoff.Proto.InvestApi.V1.PostStopOrderResponse.Parser, new[]{ "StopOrderId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Tinkoff.Proto.InvestApi.V1.GetStopOrdersRequest), global::Tinkoff.Proto.InvestApi.V1.GetStopOrdersRequest.Parser, new[]{ "AccountId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Tinkoff.Proto.InvestApi.V1.GetStopOrdersResponse), global::Tinkoff.Proto.InvestApi.V1.GetStopOrdersResponse.Parser, new[]{ "StopOrders" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Tinkoff.Proto.InvestApi.V1.CancelStopOrderRequest), global::Tinkoff.Proto.InvestApi.V1.CancelStopOrderRequest.Parser, new[]{ "AccountId", "StopOrderId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Tinkoff.Proto.InvestApi.V1.CancelStopOrderResponse), global::Tinkoff.Proto.InvestApi.V1.CancelStopOrderResponse.Parser, new[]{ "Time" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Tinkoff.Proto.InvestApi.V1.StopOrder), global::Tinkoff.Proto.InvestApi.V1.StopOrder.Parser, new[]{ "StopOrderId", "LotsRequested", "Figi", "Direction", "Currency", "OrderType", "CreateDate", "ActivationDateTime", "ExpirationTime", "Price", "StopPrice" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///Направление сделки стоп-заявки.
  /// </summary>
  public enum StopOrderDirection {
    /// <summary>
    ///Значение не указано
    /// </summary>
    [pbr::OriginalName("STOP_ORDER_DIRECTION_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    ///Покупка
    /// </summary>
    [pbr::OriginalName("STOP_ORDER_DIRECTION_BUY")] Buy = 1,
    /// <summary>
    ///Продажа
    /// </summary>
    [pbr::OriginalName("STOP_ORDER_DIRECTION_SELL")] Sell = 2,
  }

  /// <summary>
  ///Тип экспирации стоп-заявке.
  /// </summary>
  public enum StopOrderExpirationType {
    /// <summary>
    ///Значение не указано.
    /// </summary>
    [pbr::OriginalName("STOP_ORDER_EXPIRATION_TYPE_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    ///Действительно до отмены.
    /// </summary>
    [pbr::OriginalName("STOP_ORDER_EXPIRATION_TYPE_GOOD_TILL_CANCEL")] GoodTillCancel = 1,
    /// <summary>
    ///Действительно до даты снятия.
    /// </summary>
    [pbr::OriginalName("STOP_ORDER_EXPIRATION_TYPE_GOOD_TILL_DATE")] GoodTillDate = 2,
  }

  /// <summary>
  ///Тип стоп-заявки.
  /// </summary>
  public enum StopOrderType {
    /// <summary>
    ///Значение не указано
    /// </summary>
    [pbr::OriginalName("STOP_ORDER_TYPE_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    ///Take-profit заявка
    /// </summary>
    [pbr::OriginalName("STOP_ORDER_TYPE_TAKE_PROFIT")] TakeProfit = 1,
    /// <summary>
    ///Stop-loss заявка
    /// </summary>
    [pbr::OriginalName("STOP_ORDER_TYPE_STOP_LOSS")] StopLoss = 2,
    /// <summary>
    ///Stop-limit заявка
    /// </summary>
    [pbr::OriginalName("STOP_ORDER_TYPE_STOP_LIMIT")] StopLimit = 3,
  }

  #endregion

  #region Messages
  /// <summary>
  ///Запрос выставления стоп-заявки
  /// </summary>
  public sealed partial class PostStopOrderRequest : pb::IMessage<PostStopOrderRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PostStopOrderRequest> _parser = new pb::MessageParser<PostStopOrderRequest>(() => new PostStopOrderRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PostStopOrderRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tinkoff.Proto.InvestApi.V1.StopordersReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PostStopOrderRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PostStopOrderRequest(PostStopOrderRequest other) : this() {
      figi_ = other.figi_;
      quantity_ = other.quantity_;
      price_ = other.price_ != null ? other.price_.Clone() : null;
      stopPrice_ = other.stopPrice_ != null ? other.stopPrice_.Clone() : null;
      direction_ = other.direction_;
      accountId_ = other.accountId_;
      expirationType_ = other.expirationType_;
      stopOrderType_ = other.stopOrderType_;
      expireDate_ = other.expireDate_ != null ? other.expireDate_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PostStopOrderRequest Clone() {
      return new PostStopOrderRequest(this);
    }

    /// <summary>Field number for the "figi" field.</summary>
    public const int FigiFieldNumber = 1;
    private string figi_ = "";
    /// <summary>
    ///Figi-идентификатор инструмента
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Figi {
      get { return figi_; }
      set {
        figi_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "quantity" field.</summary>
    public const int QuantityFieldNumber = 2;
    private long quantity_;
    /// <summary>
    ///Количество лотов
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Quantity {
      get { return quantity_; }
      set {
        quantity_ = value;
      }
    }

    /// <summary>Field number for the "price" field.</summary>
    public const int PriceFieldNumber = 3;
    private global::Tinkoff.Proto.InvestApi.V1.Quotation price_;
    /// <summary>
    ///Цена лота
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tinkoff.Proto.InvestApi.V1.Quotation Price {
      get { return price_; }
      set {
        price_ = value;
      }
    }

    /// <summary>Field number for the "stop_price" field.</summary>
    public const int StopPriceFieldNumber = 4;
    private global::Tinkoff.Proto.InvestApi.V1.Quotation stopPrice_;
    /// <summary>
    ///Стоп-цена заявки
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tinkoff.Proto.InvestApi.V1.Quotation StopPrice {
      get { return stopPrice_; }
      set {
        stopPrice_ = value;
      }
    }

    /// <summary>Field number for the "direction" field.</summary>
    public const int DirectionFieldNumber = 5;
    private global::Tinkoff.Proto.InvestApi.V1.StopOrderDirection direction_ = global::Tinkoff.Proto.InvestApi.V1.StopOrderDirection.Unspecified;
    /// <summary>
    ///Направление операции
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tinkoff.Proto.InvestApi.V1.StopOrderDirection Direction {
      get { return direction_; }
      set {
        direction_ = value;
      }
    }

    /// <summary>Field number for the "account_id" field.</summary>
    public const int AccountIdFieldNumber = 6;
    private string accountId_ = "";
    /// <summary>
    ///Номер счёта
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AccountId {
      get { return accountId_; }
      set {
        accountId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "expiration_type" field.</summary>
    public const int ExpirationTypeFieldNumber = 7;
    private global::Tinkoff.Proto.InvestApi.V1.StopOrderExpirationType expirationType_ = global::Tinkoff.Proto.InvestApi.V1.StopOrderExpirationType.Unspecified;
    /// <summary>
    ///Тип экспирации заявки
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tinkoff.Proto.InvestApi.V1.StopOrderExpirationType ExpirationType {
      get { return expirationType_; }
      set {
        expirationType_ = value;
      }
    }

    /// <summary>Field number for the "stop_order_type" field.</summary>
    public const int StopOrderTypeFieldNumber = 8;
    private global::Tinkoff.Proto.InvestApi.V1.StopOrderType stopOrderType_ = global::Tinkoff.Proto.InvestApi.V1.StopOrderType.Unspecified;
    /// <summary>
    ///Тип заявки
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tinkoff.Proto.InvestApi.V1.StopOrderType StopOrderType {
      get { return stopOrderType_; }
      set {
        stopOrderType_ = value;
      }
    }

    /// <summary>Field number for the "expire_date" field.</summary>
    public const int ExpireDateFieldNumber = 9;
    private global::Google.Protobuf.WellKnownTypes.Timestamp expireDate_;
    /// <summary>
    ///Дата и время окончания действия стоп-заявки в часовом поясе UTC. **Для ExpirationType = GoodTillDate заполнение обязательно**.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp ExpireDate {
      get { return expireDate_; }
      set {
        expireDate_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PostStopOrderRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PostStopOrderRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Figi != other.Figi) return false;
      if (Quantity != other.Quantity) return false;
      if (!object.Equals(Price, other.Price)) return false;
      if (!object.Equals(StopPrice, other.StopPrice)) return false;
      if (Direction != other.Direction) return false;
      if (AccountId != other.AccountId) return false;
      if (ExpirationType != other.ExpirationType) return false;
      if (StopOrderType != other.StopOrderType) return false;
      if (!object.Equals(ExpireDate, other.ExpireDate)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Figi.Length != 0) hash ^= Figi.GetHashCode();
      if (Quantity != 0L) hash ^= Quantity.GetHashCode();
      if (price_ != null) hash ^= Price.GetHashCode();
      if (stopPrice_ != null) hash ^= StopPrice.GetHashCode();
      if (Direction != global::Tinkoff.Proto.InvestApi.V1.StopOrderDirection.Unspecified) hash ^= Direction.GetHashCode();
      if (AccountId.Length != 0) hash ^= AccountId.GetHashCode();
      if (ExpirationType != global::Tinkoff.Proto.InvestApi.V1.StopOrderExpirationType.Unspecified) hash ^= ExpirationType.GetHashCode();
      if (StopOrderType != global::Tinkoff.Proto.InvestApi.V1.StopOrderType.Unspecified) hash ^= StopOrderType.GetHashCode();
      if (expireDate_ != null) hash ^= ExpireDate.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Figi.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Figi);
      }
      if (Quantity != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Quantity);
      }
      if (price_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Price);
      }
      if (stopPrice_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(StopPrice);
      }
      if (Direction != global::Tinkoff.Proto.InvestApi.V1.StopOrderDirection.Unspecified) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Direction);
      }
      if (AccountId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(AccountId);
      }
      if (ExpirationType != global::Tinkoff.Proto.InvestApi.V1.StopOrderExpirationType.Unspecified) {
        output.WriteRawTag(56);
        output.WriteEnum((int) ExpirationType);
      }
      if (StopOrderType != global::Tinkoff.Proto.InvestApi.V1.StopOrderType.Unspecified) {
        output.WriteRawTag(64);
        output.WriteEnum((int) StopOrderType);
      }
      if (expireDate_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(ExpireDate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Figi.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Figi);
      }
      if (Quantity != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Quantity);
      }
      if (price_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Price);
      }
      if (stopPrice_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(StopPrice);
      }
      if (Direction != global::Tinkoff.Proto.InvestApi.V1.StopOrderDirection.Unspecified) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Direction);
      }
      if (AccountId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(AccountId);
      }
      if (ExpirationType != global::Tinkoff.Proto.InvestApi.V1.StopOrderExpirationType.Unspecified) {
        output.WriteRawTag(56);
        output.WriteEnum((int) ExpirationType);
      }
      if (StopOrderType != global::Tinkoff.Proto.InvestApi.V1.StopOrderType.Unspecified) {
        output.WriteRawTag(64);
        output.WriteEnum((int) StopOrderType);
      }
      if (expireDate_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(ExpireDate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Figi.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Figi);
      }
      if (Quantity != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Quantity);
      }
      if (price_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Price);
      }
      if (stopPrice_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StopPrice);
      }
      if (Direction != global::Tinkoff.Proto.InvestApi.V1.StopOrderDirection.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Direction);
      }
      if (AccountId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AccountId);
      }
      if (ExpirationType != global::Tinkoff.Proto.InvestApi.V1.StopOrderExpirationType.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ExpirationType);
      }
      if (StopOrderType != global::Tinkoff.Proto.InvestApi.V1.StopOrderType.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) StopOrderType);
      }
      if (expireDate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ExpireDate);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PostStopOrderRequest other) {
      if (other == null) {
        return;
      }
      if (other.Figi.Length != 0) {
        Figi = other.Figi;
      }
      if (other.Quantity != 0L) {
        Quantity = other.Quantity;
      }
      if (other.price_ != null) {
        if (price_ == null) {
          Price = new global::Tinkoff.Proto.InvestApi.V1.Quotation();
        }
        Price.MergeFrom(other.Price);
      }
      if (other.stopPrice_ != null) {
        if (stopPrice_ == null) {
          StopPrice = new global::Tinkoff.Proto.InvestApi.V1.Quotation();
        }
        StopPrice.MergeFrom(other.StopPrice);
      }
      if (other.Direction != global::Tinkoff.Proto.InvestApi.V1.StopOrderDirection.Unspecified) {
        Direction = other.Direction;
      }
      if (other.AccountId.Length != 0) {
        AccountId = other.AccountId;
      }
      if (other.ExpirationType != global::Tinkoff.Proto.InvestApi.V1.StopOrderExpirationType.Unspecified) {
        ExpirationType = other.ExpirationType;
      }
      if (other.StopOrderType != global::Tinkoff.Proto.InvestApi.V1.StopOrderType.Unspecified) {
        StopOrderType = other.StopOrderType;
      }
      if (other.expireDate_ != null) {
        if (expireDate_ == null) {
          ExpireDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        ExpireDate.MergeFrom(other.ExpireDate);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Figi = input.ReadString();
            break;
          }
          case 16: {
            Quantity = input.ReadInt64();
            break;
          }
          case 26: {
            if (price_ == null) {
              Price = new global::Tinkoff.Proto.InvestApi.V1.Quotation();
            }
            input.ReadMessage(Price);
            break;
          }
          case 34: {
            if (stopPrice_ == null) {
              StopPrice = new global::Tinkoff.Proto.InvestApi.V1.Quotation();
            }
            input.ReadMessage(StopPrice);
            break;
          }
          case 40: {
            Direction = (global::Tinkoff.Proto.InvestApi.V1.StopOrderDirection) input.ReadEnum();
            break;
          }
          case 50: {
            AccountId = input.ReadString();
            break;
          }
          case 56: {
            ExpirationType = (global::Tinkoff.Proto.InvestApi.V1.StopOrderExpirationType) input.ReadEnum();
            break;
          }
          case 64: {
            StopOrderType = (global::Tinkoff.Proto.InvestApi.V1.StopOrderType) input.ReadEnum();
            break;
          }
          case 74: {
            if (expireDate_ == null) {
              ExpireDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ExpireDate);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Figi = input.ReadString();
            break;
          }
          case 16: {
            Quantity = input.ReadInt64();
            break;
          }
          case 26: {
            if (price_ == null) {
              Price = new global::Tinkoff.Proto.InvestApi.V1.Quotation();
            }
            input.ReadMessage(Price);
            break;
          }
          case 34: {
            if (stopPrice_ == null) {
              StopPrice = new global::Tinkoff.Proto.InvestApi.V1.Quotation();
            }
            input.ReadMessage(StopPrice);
            break;
          }
          case 40: {
            Direction = (global::Tinkoff.Proto.InvestApi.V1.StopOrderDirection) input.ReadEnum();
            break;
          }
          case 50: {
            AccountId = input.ReadString();
            break;
          }
          case 56: {
            ExpirationType = (global::Tinkoff.Proto.InvestApi.V1.StopOrderExpirationType) input.ReadEnum();
            break;
          }
          case 64: {
            StopOrderType = (global::Tinkoff.Proto.InvestApi.V1.StopOrderType) input.ReadEnum();
            break;
          }
          case 74: {
            if (expireDate_ == null) {
              ExpireDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ExpireDate);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///Результат выставления стоп-заявки.
  /// </summary>
  public sealed partial class PostStopOrderResponse : pb::IMessage<PostStopOrderResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PostStopOrderResponse> _parser = new pb::MessageParser<PostStopOrderResponse>(() => new PostStopOrderResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PostStopOrderResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tinkoff.Proto.InvestApi.V1.StopordersReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PostStopOrderResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PostStopOrderResponse(PostStopOrderResponse other) : this() {
      stopOrderId_ = other.stopOrderId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PostStopOrderResponse Clone() {
      return new PostStopOrderResponse(this);
    }

    /// <summary>Field number for the "stop_order_id" field.</summary>
    public const int StopOrderIdFieldNumber = 1;
    private string stopOrderId_ = "";
    /// <summary>
    ///Уникальный идентификатор стоп-заявки.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StopOrderId {
      get { return stopOrderId_; }
      set {
        stopOrderId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PostStopOrderResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PostStopOrderResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StopOrderId != other.StopOrderId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (StopOrderId.Length != 0) hash ^= StopOrderId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (StopOrderId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(StopOrderId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (StopOrderId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(StopOrderId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (StopOrderId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StopOrderId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PostStopOrderResponse other) {
      if (other == null) {
        return;
      }
      if (other.StopOrderId.Length != 0) {
        StopOrderId = other.StopOrderId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            StopOrderId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            StopOrderId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///Запрос получения списка активных стоп-заявок.
  /// </summary>
  public sealed partial class GetStopOrdersRequest : pb::IMessage<GetStopOrdersRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetStopOrdersRequest> _parser = new pb::MessageParser<GetStopOrdersRequest>(() => new GetStopOrdersRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetStopOrdersRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tinkoff.Proto.InvestApi.V1.StopordersReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetStopOrdersRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetStopOrdersRequest(GetStopOrdersRequest other) : this() {
      accountId_ = other.accountId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetStopOrdersRequest Clone() {
      return new GetStopOrdersRequest(this);
    }

    /// <summary>Field number for the "account_id" field.</summary>
    public const int AccountIdFieldNumber = 1;
    private string accountId_ = "";
    /// <summary>
    ///Идентификатор счёта клиента
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AccountId {
      get { return accountId_; }
      set {
        accountId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetStopOrdersRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetStopOrdersRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AccountId != other.AccountId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AccountId.Length != 0) hash ^= AccountId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AccountId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AccountId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AccountId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AccountId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AccountId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AccountId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetStopOrdersRequest other) {
      if (other == null) {
        return;
      }
      if (other.AccountId.Length != 0) {
        AccountId = other.AccountId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AccountId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            AccountId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///Список активных стоп-заявок.
  /// </summary>
  public sealed partial class GetStopOrdersResponse : pb::IMessage<GetStopOrdersResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetStopOrdersResponse> _parser = new pb::MessageParser<GetStopOrdersResponse>(() => new GetStopOrdersResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetStopOrdersResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tinkoff.Proto.InvestApi.V1.StopordersReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetStopOrdersResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetStopOrdersResponse(GetStopOrdersResponse other) : this() {
      stopOrders_ = other.stopOrders_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetStopOrdersResponse Clone() {
      return new GetStopOrdersResponse(this);
    }

    /// <summary>Field number for the "stop_orders" field.</summary>
    public const int StopOrdersFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Tinkoff.Proto.InvestApi.V1.StopOrder> _repeated_stopOrders_codec
        = pb::FieldCodec.ForMessage(10, global::Tinkoff.Proto.InvestApi.V1.StopOrder.Parser);
    private readonly pbc::RepeatedField<global::Tinkoff.Proto.InvestApi.V1.StopOrder> stopOrders_ = new pbc::RepeatedField<global::Tinkoff.Proto.InvestApi.V1.StopOrder>();
    /// <summary>
    ///Массив стоп-заявок по счёту
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Tinkoff.Proto.InvestApi.V1.StopOrder> StopOrders {
      get { return stopOrders_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetStopOrdersResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetStopOrdersResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!stopOrders_.Equals(other.stopOrders_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= stopOrders_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      stopOrders_.WriteTo(output, _repeated_stopOrders_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      stopOrders_.WriteTo(ref output, _repeated_stopOrders_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += stopOrders_.CalculateSize(_repeated_stopOrders_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetStopOrdersResponse other) {
      if (other == null) {
        return;
      }
      stopOrders_.Add(other.stopOrders_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            stopOrders_.AddEntriesFrom(input, _repeated_stopOrders_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            stopOrders_.AddEntriesFrom(ref input, _repeated_stopOrders_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///Запрос отмены выставленной стоп-заявки.
  /// </summary>
  public sealed partial class CancelStopOrderRequest : pb::IMessage<CancelStopOrderRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CancelStopOrderRequest> _parser = new pb::MessageParser<CancelStopOrderRequest>(() => new CancelStopOrderRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CancelStopOrderRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tinkoff.Proto.InvestApi.V1.StopordersReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CancelStopOrderRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CancelStopOrderRequest(CancelStopOrderRequest other) : this() {
      accountId_ = other.accountId_;
      stopOrderId_ = other.stopOrderId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CancelStopOrderRequest Clone() {
      return new CancelStopOrderRequest(this);
    }

    /// <summary>Field number for the "account_id" field.</summary>
    public const int AccountIdFieldNumber = 1;
    private string accountId_ = "";
    /// <summary>
    ///Идентификатор счёта клиента
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AccountId {
      get { return accountId_; }
      set {
        accountId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "stop_order_id" field.</summary>
    public const int StopOrderIdFieldNumber = 2;
    private string stopOrderId_ = "";
    /// <summary>
    ///Уникальный идентификатор стоп-заявки.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StopOrderId {
      get { return stopOrderId_; }
      set {
        stopOrderId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CancelStopOrderRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CancelStopOrderRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AccountId != other.AccountId) return false;
      if (StopOrderId != other.StopOrderId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AccountId.Length != 0) hash ^= AccountId.GetHashCode();
      if (StopOrderId.Length != 0) hash ^= StopOrderId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AccountId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AccountId);
      }
      if (StopOrderId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(StopOrderId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AccountId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AccountId);
      }
      if (StopOrderId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(StopOrderId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AccountId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AccountId);
      }
      if (StopOrderId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StopOrderId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CancelStopOrderRequest other) {
      if (other == null) {
        return;
      }
      if (other.AccountId.Length != 0) {
        AccountId = other.AccountId;
      }
      if (other.StopOrderId.Length != 0) {
        StopOrderId = other.StopOrderId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AccountId = input.ReadString();
            break;
          }
          case 18: {
            StopOrderId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            AccountId = input.ReadString();
            break;
          }
          case 18: {
            StopOrderId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///Результат отмены выставленной стоп-заявки.
  /// </summary>
  public sealed partial class CancelStopOrderResponse : pb::IMessage<CancelStopOrderResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CancelStopOrderResponse> _parser = new pb::MessageParser<CancelStopOrderResponse>(() => new CancelStopOrderResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CancelStopOrderResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tinkoff.Proto.InvestApi.V1.StopordersReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CancelStopOrderResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CancelStopOrderResponse(CancelStopOrderResponse other) : this() {
      time_ = other.time_ != null ? other.time_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CancelStopOrderResponse Clone() {
      return new CancelStopOrderResponse(this);
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp time_;
    /// <summary>
    ///Время отмены заявки в часовом поясе UTC.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CancelStopOrderResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CancelStopOrderResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Time, other.Time)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (time_ != null) hash ^= Time.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (time_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Time);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (time_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Time);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (time_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Time);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CancelStopOrderResponse other) {
      if (other == null) {
        return;
      }
      if (other.time_ != null) {
        if (time_ == null) {
          Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Time.MergeFrom(other.Time);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (time_ == null) {
              Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Time);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (time_ == null) {
              Time = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Time);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///Информация о стоп-заявке.
  /// </summary>
  public sealed partial class StopOrder : pb::IMessage<StopOrder>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StopOrder> _parser = new pb::MessageParser<StopOrder>(() => new StopOrder());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<StopOrder> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tinkoff.Proto.InvestApi.V1.StopordersReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StopOrder() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StopOrder(StopOrder other) : this() {
      stopOrderId_ = other.stopOrderId_;
      lotsRequested_ = other.lotsRequested_;
      figi_ = other.figi_;
      direction_ = other.direction_;
      currency_ = other.currency_;
      orderType_ = other.orderType_;
      createDate_ = other.createDate_ != null ? other.createDate_.Clone() : null;
      activationDateTime_ = other.activationDateTime_ != null ? other.activationDateTime_.Clone() : null;
      expirationTime_ = other.expirationTime_ != null ? other.expirationTime_.Clone() : null;
      price_ = other.price_ != null ? other.price_.Clone() : null;
      stopPrice_ = other.stopPrice_ != null ? other.stopPrice_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StopOrder Clone() {
      return new StopOrder(this);
    }

    /// <summary>Field number for the "stop_order_id" field.</summary>
    public const int StopOrderIdFieldNumber = 1;
    private string stopOrderId_ = "";
    /// <summary>
    ///Идентификатор-идентификатор стоп-заявки
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StopOrderId {
      get { return stopOrderId_; }
      set {
        stopOrderId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "lots_requested" field.</summary>
    public const int LotsRequestedFieldNumber = 2;
    private long lotsRequested_;
    /// <summary>
    ///Запрошено лотов
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long LotsRequested {
      get { return lotsRequested_; }
      set {
        lotsRequested_ = value;
      }
    }

    /// <summary>Field number for the "figi" field.</summary>
    public const int FigiFieldNumber = 3;
    private string figi_ = "";
    /// <summary>
    ///Figi-идентификатор инструмента
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Figi {
      get { return figi_; }
      set {
        figi_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "direction" field.</summary>
    public const int DirectionFieldNumber = 4;
    private global::Tinkoff.Proto.InvestApi.V1.StopOrderDirection direction_ = global::Tinkoff.Proto.InvestApi.V1.StopOrderDirection.Unspecified;
    /// <summary>
    ///Направление операции
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tinkoff.Proto.InvestApi.V1.StopOrderDirection Direction {
      get { return direction_; }
      set {
        direction_ = value;
      }
    }

    /// <summary>Field number for the "currency" field.</summary>
    public const int CurrencyFieldNumber = 5;
    private string currency_ = "";
    /// <summary>
    ///Валюта стоп-заявки
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Currency {
      get { return currency_; }
      set {
        currency_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "order_type" field.</summary>
    public const int OrderTypeFieldNumber = 6;
    private global::Tinkoff.Proto.InvestApi.V1.StopOrderType orderType_ = global::Tinkoff.Proto.InvestApi.V1.StopOrderType.Unspecified;
    /// <summary>
    ///Тип стоп-заявки
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tinkoff.Proto.InvestApi.V1.StopOrderType OrderType {
      get { return orderType_; }
      set {
        orderType_ = value;
      }
    }

    /// <summary>Field number for the "create_date" field.</summary>
    public const int CreateDateFieldNumber = 7;
    private global::Google.Protobuf.WellKnownTypes.Timestamp createDate_;
    /// <summary>
    ///Дата и время выставления заявки в часовом поясе UTC.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp CreateDate {
      get { return createDate_; }
      set {
        createDate_ = value;
      }
    }

    /// <summary>Field number for the "activation_date_time" field.</summary>
    public const int ActivationDateTimeFieldNumber = 8;
    private global::Google.Protobuf.WellKnownTypes.Timestamp activationDateTime_;
    /// <summary>
    ///Дата и время конвертации стоп-заявки в биржевую в часовом поясе UTC.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp ActivationDateTime {
      get { return activationDateTime_; }
      set {
        activationDateTime_ = value;
      }
    }

    /// <summary>Field number for the "expiration_time" field.</summary>
    public const int ExpirationTimeFieldNumber = 9;
    private global::Google.Protobuf.WellKnownTypes.Timestamp expirationTime_;
    /// <summary>
    ///Дата и время снятия заявки в часовом поясе UTC.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp ExpirationTime {
      get { return expirationTime_; }
      set {
        expirationTime_ = value;
      }
    }

    /// <summary>Field number for the "price" field.</summary>
    public const int PriceFieldNumber = 10;
    private global::Tinkoff.Proto.InvestApi.V1.MoneyValue price_;
    /// <summary>
    ///Цена заявки
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tinkoff.Proto.InvestApi.V1.MoneyValue Price {
      get { return price_; }
      set {
        price_ = value;
      }
    }

    /// <summary>Field number for the "stop_price" field.</summary>
    public const int StopPriceFieldNumber = 11;
    private global::Tinkoff.Proto.InvestApi.V1.MoneyValue stopPrice_;
    /// <summary>
    ///Цена активации стоп-заявки
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Tinkoff.Proto.InvestApi.V1.MoneyValue StopPrice {
      get { return stopPrice_; }
      set {
        stopPrice_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as StopOrder);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(StopOrder other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StopOrderId != other.StopOrderId) return false;
      if (LotsRequested != other.LotsRequested) return false;
      if (Figi != other.Figi) return false;
      if (Direction != other.Direction) return false;
      if (Currency != other.Currency) return false;
      if (OrderType != other.OrderType) return false;
      if (!object.Equals(CreateDate, other.CreateDate)) return false;
      if (!object.Equals(ActivationDateTime, other.ActivationDateTime)) return false;
      if (!object.Equals(ExpirationTime, other.ExpirationTime)) return false;
      if (!object.Equals(Price, other.Price)) return false;
      if (!object.Equals(StopPrice, other.StopPrice)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (StopOrderId.Length != 0) hash ^= StopOrderId.GetHashCode();
      if (LotsRequested != 0L) hash ^= LotsRequested.GetHashCode();
      if (Figi.Length != 0) hash ^= Figi.GetHashCode();
      if (Direction != global::Tinkoff.Proto.InvestApi.V1.StopOrderDirection.Unspecified) hash ^= Direction.GetHashCode();
      if (Currency.Length != 0) hash ^= Currency.GetHashCode();
      if (OrderType != global::Tinkoff.Proto.InvestApi.V1.StopOrderType.Unspecified) hash ^= OrderType.GetHashCode();
      if (createDate_ != null) hash ^= CreateDate.GetHashCode();
      if (activationDateTime_ != null) hash ^= ActivationDateTime.GetHashCode();
      if (expirationTime_ != null) hash ^= ExpirationTime.GetHashCode();
      if (price_ != null) hash ^= Price.GetHashCode();
      if (stopPrice_ != null) hash ^= StopPrice.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (StopOrderId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(StopOrderId);
      }
      if (LotsRequested != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(LotsRequested);
      }
      if (Figi.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Figi);
      }
      if (Direction != global::Tinkoff.Proto.InvestApi.V1.StopOrderDirection.Unspecified) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Direction);
      }
      if (Currency.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Currency);
      }
      if (OrderType != global::Tinkoff.Proto.InvestApi.V1.StopOrderType.Unspecified) {
        output.WriteRawTag(48);
        output.WriteEnum((int) OrderType);
      }
      if (createDate_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(CreateDate);
      }
      if (activationDateTime_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(ActivationDateTime);
      }
      if (expirationTime_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(ExpirationTime);
      }
      if (price_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(Price);
      }
      if (stopPrice_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(StopPrice);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (StopOrderId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(StopOrderId);
      }
      if (LotsRequested != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(LotsRequested);
      }
      if (Figi.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Figi);
      }
      if (Direction != global::Tinkoff.Proto.InvestApi.V1.StopOrderDirection.Unspecified) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Direction);
      }
      if (Currency.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Currency);
      }
      if (OrderType != global::Tinkoff.Proto.InvestApi.V1.StopOrderType.Unspecified) {
        output.WriteRawTag(48);
        output.WriteEnum((int) OrderType);
      }
      if (createDate_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(CreateDate);
      }
      if (activationDateTime_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(ActivationDateTime);
      }
      if (expirationTime_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(ExpirationTime);
      }
      if (price_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(Price);
      }
      if (stopPrice_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(StopPrice);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (StopOrderId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StopOrderId);
      }
      if (LotsRequested != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LotsRequested);
      }
      if (Figi.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Figi);
      }
      if (Direction != global::Tinkoff.Proto.InvestApi.V1.StopOrderDirection.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Direction);
      }
      if (Currency.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Currency);
      }
      if (OrderType != global::Tinkoff.Proto.InvestApi.V1.StopOrderType.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) OrderType);
      }
      if (createDate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreateDate);
      }
      if (activationDateTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ActivationDateTime);
      }
      if (expirationTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ExpirationTime);
      }
      if (price_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Price);
      }
      if (stopPrice_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StopPrice);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(StopOrder other) {
      if (other == null) {
        return;
      }
      if (other.StopOrderId.Length != 0) {
        StopOrderId = other.StopOrderId;
      }
      if (other.LotsRequested != 0L) {
        LotsRequested = other.LotsRequested;
      }
      if (other.Figi.Length != 0) {
        Figi = other.Figi;
      }
      if (other.Direction != global::Tinkoff.Proto.InvestApi.V1.StopOrderDirection.Unspecified) {
        Direction = other.Direction;
      }
      if (other.Currency.Length != 0) {
        Currency = other.Currency;
      }
      if (other.OrderType != global::Tinkoff.Proto.InvestApi.V1.StopOrderType.Unspecified) {
        OrderType = other.OrderType;
      }
      if (other.createDate_ != null) {
        if (createDate_ == null) {
          CreateDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        CreateDate.MergeFrom(other.CreateDate);
      }
      if (other.activationDateTime_ != null) {
        if (activationDateTime_ == null) {
          ActivationDateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        ActivationDateTime.MergeFrom(other.ActivationDateTime);
      }
      if (other.expirationTime_ != null) {
        if (expirationTime_ == null) {
          ExpirationTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        ExpirationTime.MergeFrom(other.ExpirationTime);
      }
      if (other.price_ != null) {
        if (price_ == null) {
          Price = new global::Tinkoff.Proto.InvestApi.V1.MoneyValue();
        }
        Price.MergeFrom(other.Price);
      }
      if (other.stopPrice_ != null) {
        if (stopPrice_ == null) {
          StopPrice = new global::Tinkoff.Proto.InvestApi.V1.MoneyValue();
        }
        StopPrice.MergeFrom(other.StopPrice);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            StopOrderId = input.ReadString();
            break;
          }
          case 16: {
            LotsRequested = input.ReadInt64();
            break;
          }
          case 26: {
            Figi = input.ReadString();
            break;
          }
          case 32: {
            Direction = (global::Tinkoff.Proto.InvestApi.V1.StopOrderDirection) input.ReadEnum();
            break;
          }
          case 42: {
            Currency = input.ReadString();
            break;
          }
          case 48: {
            OrderType = (global::Tinkoff.Proto.InvestApi.V1.StopOrderType) input.ReadEnum();
            break;
          }
          case 58: {
            if (createDate_ == null) {
              CreateDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreateDate);
            break;
          }
          case 66: {
            if (activationDateTime_ == null) {
              ActivationDateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ActivationDateTime);
            break;
          }
          case 74: {
            if (expirationTime_ == null) {
              ExpirationTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ExpirationTime);
            break;
          }
          case 82: {
            if (price_ == null) {
              Price = new global::Tinkoff.Proto.InvestApi.V1.MoneyValue();
            }
            input.ReadMessage(Price);
            break;
          }
          case 90: {
            if (stopPrice_ == null) {
              StopPrice = new global::Tinkoff.Proto.InvestApi.V1.MoneyValue();
            }
            input.ReadMessage(StopPrice);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            StopOrderId = input.ReadString();
            break;
          }
          case 16: {
            LotsRequested = input.ReadInt64();
            break;
          }
          case 26: {
            Figi = input.ReadString();
            break;
          }
          case 32: {
            Direction = (global::Tinkoff.Proto.InvestApi.V1.StopOrderDirection) input.ReadEnum();
            break;
          }
          case 42: {
            Currency = input.ReadString();
            break;
          }
          case 48: {
            OrderType = (global::Tinkoff.Proto.InvestApi.V1.StopOrderType) input.ReadEnum();
            break;
          }
          case 58: {
            if (createDate_ == null) {
              CreateDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreateDate);
            break;
          }
          case 66: {
            if (activationDateTime_ == null) {
              ActivationDateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ActivationDateTime);
            break;
          }
          case 74: {
            if (expirationTime_ == null) {
              ExpirationTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ExpirationTime);
            break;
          }
          case 82: {
            if (price_ == null) {
              Price = new global::Tinkoff.Proto.InvestApi.V1.MoneyValue();
            }
            input.ReadMessage(Price);
            break;
          }
          case 90: {
            if (stopPrice_ == null) {
              StopPrice = new global::Tinkoff.Proto.InvestApi.V1.MoneyValue();
            }
            input.ReadMessage(StopPrice);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
